#ifndef _SSS_KCOMPAT_UOS_H_
#define _SSS_KCOMPAT_UOS_H_
#ifdef __UOS__

#if IS_ENABLED(CONFIG_NET_DEVLINK)
#ifndef HAVE_DEVLINK_FLASH_UPDATE_PARAMS
#define HAVE_DEVLINK_FLASH_UPDATE_PARAMS
#endif
#endif

#if (KERNEL_VERSION(4, 19, 0) == LINUX_VERSION_CODE)
#ifdef HAVE_DEVLINK_FLASH_UPDATE_PARAMS
#undef HAVE_DEVLINK_FLASH_UPDATE_PARAMS
#endif
#endif

#if (KERNEL_VERSION(4, 19, 90) == LINUX_VERSION_CODE)
#ifdef HAVE_DEVLINK_FLASH_UPDATE_PARAMS
#undef HAVE_DEVLINK_FLASH_UPDATE_PARAMS
#endif
#endif


#endif

#endif

