obj-y     = base.o netbind.o
obj-y     += ttools/
obj-y     += shield_mounts.o
obj-y	  += release_suffix.o
obj-y	  += netatop/
obj-y	  += trackgpu.o
obj-$(CONFIG_IRQ_LATENCY)	+= irqlatency/
obj-$(CONFIG_KPATCH)	+= kpatch/
